language: python
dist: xenial
python:
  - 3.6
  - 3.7
cache: pip
before_install:
  - pip install -U poetry
install:
  - poetry install
before_script:
  - pip install -U tox-travis
  - pip install -U codecov
script:
  - tox
before_deploy:
  - poetry build
deploy:
  provider: script
  script: poetry publish --username $PYPI_USER --password $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
after_success:
  - codecov
