language: python
dist: xenial
cache: pip
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      python:
        - 3.6
        - 3.7
      install: skip
      before_script:
        - pip install -U poetry tox-travis codecov
      script:
        - tox
    - stage: deploy
      python: 3.7
      script: skip
      before_install:
        - pip install -U poetry
      install:
        - poetry install
      before_deploy:
        - poetry build
      deploy:
        provider: script
        script: poetry publish --username $PYPI_USER --password $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
      after_success:
        - codecov
