language: python
dist: xenial
python:
  - 3.6
  - 3.7
cache: pip
before_install:
  - pip install -U poetry
install:
  - poetry install
before_script:
  - pip install -U tox-travis codecov
script:
  - tox
before_deploy:
  - poetry build
after_success:
  - codecov
jobs:
  include:
    - stage: test
      install: skip
      after_success: skip
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: poetry publish --username $PYPI_USER --password $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
