[settings]
port = 80
loglevel = "DEBUG"
tests_per_day = 2

[tests]

  [tests.ndt7]
  enabled = 1

[exporters]

  [exporters.localhost]
  type = local
  path = /tmp

  [exporters.host1]
  type = scp
  target = "192.168.1.1:/var/spool/"
  port = 22
  username = "murakami"
  password = "murakami"
  private_key = "/home/murakami/.ssh/id_rsa"
