[tool.poetry]
name = "murakami"
version = "0.1.0"
description = "A webthings-compliant network measurement tool from M-Lab."
authors = ["Josh King <josh@throneless.tech>", "Rae Gaines <rae@throneless.tech>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/throneless-tech/murakami"

[tool.poetry.scripts]
murakami = 'murakami.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"
webthing = "^0.12.0"
configargparse = "^0.14.0"
tomlkit = "^0.5.5"
apscheduler = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.4"

[tool.poetry.plugins."murakami.runners"]
"ndt7" = "murakami.runners.ndt7:Ndt7Runner"
#"speedtest" = "murakami.runners.speedtest:SpeedtestClient"
#"wehe" = "murakami.runners.wehe:WeheClient"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# Runners
[tool.poetry.plugins."murakami.runners"]
"dash" = "murakami.runners.dash:DashClient"
"ndt7" = "murakami.runners.ndt7:Ndt7Client"
"speedtest" = "murakami.runners.speedtest:SpeedtestClient"

# Exporters
[tool.poetry.plugins."murakami.exporters"]
"scp" = "murakami.exporters.scp:SCPExporter"